ARDUINO = 100
ARDUINO_DIR = /usr/share/arduino
USER_LIB_PATH = libs
AVRDUDE_ARD_PROGRAMMER = linuxgpio
AVRDUDE_OPTS = -v
BOARD_TAG    = uno
ARDUINO_PORT = /dev/ttyAMA0
ARDUINO_LIBS = RemoteSwitch NewRemoteSwitch RemoteSensor InterruptChain DHT11 Timer BH1750 Wire
include /usr/share/arduino/Arduino.mk